### ISSUE TITLE
Python 3.12 + Ubuntu 22.04: findlblas fails to install system installed OpenBLAS/BLIS/ATLAS

### ISSUE THREAD

**Issue by samimia-swks** [david-cortes/findblas#6] opened 2024-05-16 04:13 UTC
On Ubuntu 22 and python 3.9.6, findblas is able to find openblas installed with apt-get: 

```
$ apt list --installed | grep blas
libblas-dev/jammy,now 3.10.0-2ubuntu1 amd64 [installed]
libblas3/jammy,now 3.10.0-2ubuntu1 amd64 [installed,automatic]
libgraphblas-dev/jammy,now 6.1.4+dfsg-2 amd64 [installed,automatic]
libgraphblas6/jammy,now 6.1.4+dfsg-2 amd64 [installed,automatic]
libopenblas-dev/jammy,now 0.3.20+ds-1 amd64 [installed]
libopenblas-pthread-dev/jammy,now 0.3.20+ds-1 amd64 [installed,automatic]
libopenblas0-pthread/jammy,now 0.3.20+ds-1 amd64 [installed,automatic]
libopenblas0/jammy,now 0.3.20+ds-1 amd64 [installed,automatic]
```
Using pyenv to switch to python 3.9.6 and running find_blas(), libopenblas.so is found: 
```
$ python
Python 3.9.6 (default, Jan 13 2024, 15:13:23)
[GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from findblas import find_blas; blas_path, blas_file, incl_path, incl_file, flags = find_blas()
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
WARNING: Package(s) not found: mkl
>>> flags
['HAS_OPENBLAS', 'HAS_UNDERSCORES']
>>> blas_file
'libopenblas.so'
>>> blas_path
'/usr/lib/x86_64-linux-gnu'
```
Using pyenv to switch to python 3.12.1 and running find_blas(), libopenblas.so is not found: 
```
$ python
Python 3.12.1 (main, May 15 2024, 18:50:06) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from findblas import find_blas; blas_path, blas_file, incl_path, incl_file, flags = find_blas()
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
WARNING: Package(s) not found: mkl
python-3.12.1/src/findblas/findblas/__init__.py:1037: UserWarning: No BLAS library found - taking SciPy's linalg.cython_blas file as library.
  warnings.warn(
>>> flags
['NO_CBLAS', 'HAS_UNDERSCORES', 'UNKNWON_BLAS']
```

Same issue exists with 3.12.1 and apt-get installed ATLAS or BLIS: 

``` 
$ apt list --installed | grep atlas
libatlas-base-dev/jammy,now 3.10.3-12ubuntu1 amd64 [installed]
libatlas3-base/jammy,now 3.10.3-12ubuntu1 amd64 [installed,automatic]
samimia@SCLSAMIMIADT01:~/git/hsp_root ‹dr-1› (python-3.12.1)

$ apt list --installed | grep blis
libblis-dev/jammy,now 0.8.1-2 amd64 [installed]
libblis-openmp-dev/jammy,now 0.8.1-2 amd64 [installed,automatic]
libblis3-openmp/jammy,now 0.8.1-2 amd64 [installed,automatic]
libblis3/jammy,now 0.8.1-2 amd64 [installed,automatic]
````

However, MKL installed with 'pip install mkl' is still found with 3.12.1. So for now I have switched to MKL...

**Comment by david-cortes** [comment] 2024-05-16 20:14
Thanks for the bug report - can reproduce even without `pyenv`. It seems to be an issue when using a python that is compiled from source, rather than being an issue with the python version - will investigate.

**Comment by david-cortes** [comment] 2024-05-17 18:17
Should be fixed now.

**Closed as completed by david-cortes** 2024-05-17 18:17 UTC
